# This file (docker-compose) will only be used in development

version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
